#!/usr/bin/env python3
"""
AIOS Ontology Stabilization Observation Report

Governance-safe observational tooling only.
Reads logs/project_cognition_snapshot.jsonl generated by D2.7.
"""

from collections import Counter, defaultdict
import json
import re
from pathlib import Path


NORMALIZATION_MAP = {
    "pool maintenance and opening": "Pool Maintenance",
    "pool maintenance and operations": "Pool Maintenance",
    "pool opening": "Pool Maintenance",
    "pool maintenance": "Pool Maintenance",
    "bread workshops": "Workshops and Teaching",
    "teaching workshops": "Workshops and Teaching",
    "workshop planning": "Workshops and Teaching",
}


def normalize(label: str) -> str:
    if not label:
        return ""
    value = re.sub(r"\s+", " ", label.strip().lower())
    return NORMALIZATION_MAP.get(value, label.strip())


def load_snapshot(snapshot_path: Path):
    if not snapshot_path.exists():
        return []

    rows = []
    with snapshot_path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except Exception:
                pass
    return rows


def main():
    snapshot_path = Path("logs/project_cognition_snapshot.jsonl")
    rows = load_snapshot(snapshot_path)

    print("=== AIOS ONTOLOGY STABILIZATION OBSERVATION ===")

    if not rows:
        print("No telemetry snapshot found.")
        print("Expected: logs/project_cognition_snapshot.jsonl")
        print("Status: observational tooling idle")
        return

    labeled_rows = [row for row in rows if row.get("suggested_project")]
    suggested = [row.get("suggested_project", "").strip() for row in labeled_rows]
    normalized = [normalize(x) for x in suggested if x]

    raw_counter = Counter(suggested)
    normalized_counter = Counter(normalized)
    source_counter = Counter(row.get("source", "unknown") for row in rows)

    print(f"Snapshot rows: {len(rows)}")
    print(f"Rows with Suggested Project labels: {len(labeled_rows)}")
    print(f"Observed Suggested Project labels: {len(raw_counter)}")
    print(f"Normalized operational domains: {len(normalized_counter)}")
    print("Sources: " + ", ".join(f"{k}={v}" for k, v in sorted(source_counter.items())))

    fragmentation = defaultdict(list)
    for raw in raw_counter:
        norm = normalize(raw)
        if raw and raw != norm:
            fragmentation[norm].append(raw)

    if fragmentation:
        print("\nPotential ontology fragmentation:")
        for canonical, variants in sorted(fragmentation.items()):
            print(f"  - {canonical}")
            for variant in sorted(set(variants)):
                print(f"      shadow_variant={variant}")

    unstable = [
        label for label, count in raw_counter.items()
        if count == 1 and len(label.split()) <= 4
    ]

    if unstable:
        print("\nLow-stability candidate labels:")
        for label in sorted(unstable)[:15]:
            print(f"  - {label}")

    drift_rows = [row for row in rows if row.get("source") == "drift_watch"]
    if drift_rows:
        print("\nDrift watch:")
        for row in drift_rows[-10:]:
            print(
                f"  - {row.get('task_title', '(untitled)')}: "
                f"existing={row.get('existing_suggested_project', '')} "
                f"proposed={row.get('suggested_project', '')}"
            )

    print("\nGovernance status:")
    print("  execution_authority_impact=none")
    print("  relation_mutations=0")
    print("  bounded_writeback=true")
    print("  observation_mode=passive")


if __name__ == "__main__":
    main()
