#!/usr/bin/env python3
"""
AIOS Ontology Stabilization Observation Report

Governance-safe observational tooling only.
Reads logs/project_cognition_snapshot.jsonl generated by Project Cognition snapshot telemetry.

D3.0 enhancement:
- resolves unresolved_relation:<id> labels in-memory using readable labels from rows with the same project_key
- reports unresolved relation labels separately from true low-stability candidate labels
"""

from collections import Counter, defaultdict
import json
import re
from pathlib import Path
from typing import Any, Mapping


NORMALIZATION_MAP = {
    "pool maintenance and opening": "Pool Maintenance",
    "pool maintenance and operations": "Pool Maintenance",
    "pool opening": "Pool Maintenance",
    "pool opening and maintenance": "Pool Maintenance",
    "pool maintenance": "Pool Maintenance",
    "bread workshops": "Workshops and Teaching",
    "teaching workshops": "Workshops and Teaching",
    "workshop planning": "Workshops and Teaching",
}


def is_unresolved_label(label: str) -> bool:
    return str(label or "").startswith("unresolved_relation:")


def is_readable_label(label: str) -> bool:
    value = str(label or "").strip()
    if not value:
        return False
    if is_unresolved_label(value):
        return False
    if value.startswith("relation:"):
        return False
    return True


def normalize(label: str) -> str:
    if not label:
        return ""
    value = re.sub(r"\s+", " ", label.strip().lower())
    return NORMALIZATION_MAP.get(value, label.strip())


def load_snapshot(snapshot_path: Path) -> list[dict[str, Any]]:
    if not snapshot_path.exists():
        return []

    rows: list[dict[str, Any]] = []
    with snapshot_path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except Exception:
                continue
            if isinstance(item, dict):
                rows.append(item)
    return rows


def build_relation_label_map(rows: list[Mapping[str, Any]]) -> dict[str, str]:
    labels_by_key: dict[str, Counter[str]] = defaultdict(Counter)

    for row in rows:
        project_key = str(row.get("project_key") or "").strip()
        label = str(row.get("suggested_project") or "").strip()
        if project_key.startswith("relation:") and is_readable_label(label):
            labels_by_key[project_key][label] += 1

    return {
        project_key: counts.most_common(1)[0][0]
        for project_key, counts in labels_by_key.items()
        if counts
    }


def resolve_rows_for_reporting(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], int, int]:
    label_by_key = build_relation_label_map(rows)
    resolved_rows: list[dict[str, Any]] = []
    resolved_count = 0
    unresolved_remaining = 0

    for row in rows:
        new_row = dict(row)
        project_key = str(new_row.get("project_key") or "").strip()
        label = str(new_row.get("suggested_project") or "").strip()

        if is_unresolved_label(label):
            replacement = label_by_key.get(project_key)
            if replacement:
                new_row["suggested_project"] = replacement
                new_row["label_resolved_from"] = label
                resolved_count += 1
            else:
                unresolved_remaining += 1

        resolved_rows.append(new_row)

    return resolved_rows, resolved_count, unresolved_remaining


def main():
    snapshot_path = Path("logs/project_cognition_snapshot.jsonl")
    raw_rows = load_snapshot(snapshot_path)
    rows, resolved_count, unresolved_remaining = resolve_rows_for_reporting(raw_rows)

    print("=== AIOS ONTOLOGY STABILIZATION OBSERVATION ===")

    if not rows:
        print("No telemetry snapshot found.")
        print("Expected: logs/project_cognition_snapshot.jsonl")
        print("Status: observational tooling idle")
        return

    labeled_rows = [row for row in rows if row.get("suggested_project")]
    suggested = [row.get("suggested_project", "").strip() for row in labeled_rows]
    normalized = [normalize(x) for x in suggested if x and not is_unresolved_label(x)]

    raw_counter = Counter(x for x in suggested if x and not is_unresolved_label(x))
    unresolved_counter = Counter(x for x in suggested if is_unresolved_label(x))
    normalized_counter = Counter(normalized)
    source_counter = Counter(row.get("source", "unknown") for row in rows)

    print(f"Snapshot rows: {len(rows)}")
    print(f"Rows with Suggested Project labels: {len(labeled_rows)}")
    print(f"Observed Suggested Project labels: {len(raw_counter)}")
    print(f"Normalized operational domains: {len(normalized_counter)}")
    print("Sources: " + ", ".join(f"{k}={v}" for k, v in sorted(source_counter.items())))

    if resolved_count:
        print(f"Resolved relation labels for report: {resolved_count}")

    if unresolved_counter:
        print("\nUnresolved relation labels remaining:")
        for label, count in sorted(unresolved_counter.items()):
            print(f"  - {label} ({count})")

    fragmentation = defaultdict(list)
    for raw in raw_counter:
        norm = normalize(raw)
        if raw and raw != norm:
            fragmentation[norm].append(raw)

    if fragmentation:
        print("\nPotential ontology fragmentation:")
        for canonical, variants in sorted(fragmentation.items()):
            print(f"  - {canonical}")
            for variant in sorted(set(variants)):
                print(f"      shadow_variant={variant}")

    unstable = [
        label for label, count in raw_counter.items()
        if count == 1 and len(label.split()) <= 4
    ]

    if unstable:
        print("\nLow-stability candidate labels:")
        for label in sorted(unstable)[:15]:
            print(f"  - {label}")

    drift_rows = [row for row in rows if row.get("source") == "drift_watch"]
    if drift_rows:
        print("\nDrift watch:")
        for row in drift_rows[-10:]:
            print(
                f"  - {row.get('task_title', '(untitled)')}: "
                f"existing={row.get('existing_suggested_project', '')} "
                f"proposed={row.get('suggested_project', '')}"
            )

    print("\nGovernance status:")
    print("  execution_authority_impact=none")
    print("  relation_mutations=0")
    print("  bounded_writeback=true")
    print("  observation_mode=passive")


if __name__ == "__main__":
    main()
